src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean" ,options={"default": false } ) 
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct(){
        $this->created_at = new \dateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }
    
    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getrooms(): ?int
    {
        return $this->rooms;
    }

    public function setrooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

}

src/Controller/Admin/PropertyController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;


class PropertyController extends AbstractController{

    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var ObjectManager
     */
    protected $em;


    public function __construct(PropertyRepository $repository , EntityManagerInterface $em){
        $this->repository = $repository;
        $this->em = $em; 
    }

    /**
     * @Route("/biens", name="property.index")
     * @return Response
     */
     public Function index(): Response
    {

        $property = $this->repository->findAllVisible();
        
        $this->em->flush();

        return $this->render('property/index.html.twig', ['current_menu' => 'properties']);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @return Response
     */
    public function show($slug, $id): Response{

        $property=$this->repository->find($id);

        return $this->render('property/show.html.twig', 
        ['property' => $property , 'current_menu' =>'properties'] );
    }

}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;


class PropertyController extends AbstractController{

    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var ObjectManager
     */
    protected $em;


    public function __construct(PropertyRepository $repository , EntityManagerInterface $em){
        $this->repository = $repository;
        $this->em = $em; 
    }

    /**
     * @Route("/biens", name="property.index")
     * @return Response
     */
     public Function index(): Response
    {

        $property = $this->repository->findAllVisible();
        
        $this->em->flush();

        return $this->render('property/index.html.twig', ['current_menu' => 'properties']);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @return Response
     */
    public function show($slug, $id): Response{

        $property=$this->repository->find($id);

        return $this->render('property/show.html.twig', 
        ['property' => $property , 'current_menu' =>'properties'] );
    }

}

templates/property/edit.html.twig
{% extends 'base.html.twig' %}

{% block Title %}location Current{% endblock %}   
{% block body %}
<div class="jumbotron txt-center">
    <div class="container mt-4">
    <h2>editer le bien</h2>  
</div>
</div>
{% endblock %}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block Title %}Agence McFly{% endblock %}   
{% block body %}

<div class="jumbotron txt-center m-t-5">
    <div class="container mt-4">
        <h1>Gerer les biens<div>
    </div>
</div>
    <h1></h1>
        <table class="container mt-4">
            <thead>
                <tr>
                    <th>Titre du bien</th>
                    <th>action</th>
                </tr>
            </thead>
            <tbody>
            {%for property in properties %}
                <td>{{property.title}}</dt>
                <td>
                    <a href="{{path('admin.property.edit', {id: property.id})}}" class="btn btn-secondary">Editer</a>
                </td>
            {% endfor %}%}
            </tbody>
        </table>


     {% for property in properties %}     </div>

       <p> <a href="{{ path( 'property.show', {id: property.id , slug: property.slug} )}}"> {{ property.title }}</a></p>
       <div>
    <p class ="card-text"> {{ property.city}} ({{property.postalCode}})</b>     </div>

     <div class="text-primary">{{ property.price}}</div>
    {% endfor %}

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block Title %}location Current{% endblock %}   
{% block body %}
<div class="jumbotron txt-center">
    <div class="container mt-4">
    <div class="row">
    <div class="col-md-8">
     h1   
    </div>
    <div class="col-md-4">    
            <h1>{{property.title}}<h1>
            <h2>{{property.rooms}} pièces - {{ property.surface}} m²<h2>
    <div class="text-primary" style="font-size: 4rem; font-weight: bold;"> {{property.Price}} € </div>
    <a href= "#" class="btn btn-primary">contacter l'agence</a>
    
    </div>
    </div>
    <p> {{property.description | nl2br}}
    </P>

</div>
{% endblock %}